project_id = "afqjogweprhgbbqyvoxm"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false

  [functions.preview-transactional-email]
    verify_jwt = false

  [functions.send-site-email]
    verify_jwt = false

