
name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install

      - run: npm run build

      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html

      - name: Add CNAME file
        run: echo "talonandtide.com" > dist/CNAME

      - name: Debug build output
        run: |
          echo "Listing contents of the root directory..."
          ls -la
          echo "Listing contents of the dist directory..."
          ls -R dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: talonandtide.com
          force_orphan: true
